server:
  port: 5001
  
spring:
  application:
    name: USER-SERVICE
    
  datasource:
    url: jdbc:mysql://localhost:3306/yt_task_user_service
    username: root
    password: cscorner
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true            # Correct spelling (was: fetch-registery)
    register-with-eureka: true
    service-Url:                    # Correct casing (was: service-Url)
      defaultZone: http://localhost:8070/eureka/

